user: slefort

bash_github: git@github.com:silefort/bash.git
tmux_github: git@github.com:silefort/tmux.git
vimrc_github: git@github.com:silefort/vim.git

dnf_apps:
  - dnf-plugins-core
  - fd-find
  - firefox
  - gnome-tweaks
  - golang
  - keepassx
  - konsole
  - python-pip
  - python2-libselinux
  - powerline
  - tmux
  - vim
